-- create table cities
create table cities (
	city_id int,
	name varchar(255) not null,
	longitute numeric not null,
	latitude numeric not null,
	primary key(city_id)
);

-- create table products
create table products (
	product_id int generated by default as identity,
	brand varchar(100) not null,
	model varchar(100) not null,
	body_type varchar(100) not null,
	year smallint not null,
	price numeric not null,
	primary key(product_id),
	CHECK (price > 0)
);

-- create table sellers
create table sellers (
	seller_id int generated by default as identity,
	city_id int not null,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	phone varchar(20) not null,
	primary key(seller_id),
	constraint fk_sellers_cities
		foreign key(city_id) 
		references cities(city_id),
	constraint uq_sellers_phone
		unique(phone)
);

-- create table customers
create table customers (
	customer_id int generated by default as identity,
	city_id int not null,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	phone varchar(20) not null,
	primary key(customer_id),
	constraint fk_customers_cities
		foreign key(city_id) 
		references cities(city_id),
	constraint uq_customers_phone
		unique(phone)
);

-- create table ads
create table ads (
	ad_id int generated by default as identity, 
	seller_id int not null,
	product_id int not null,
	title varchar(255) not null,
	description text,
	date_post date not null,
	is_bid bool default true not null,
	primary key(ad_id),
	constraint fk_ads_products
		foreign key(product_id)
		references products(product_id),
	constraint fk_ads_sellers
		foreign key(seller_id)
		references sellers(seller_id)
);

-- create table bids
create table bids (
	bid_id int generated by default as identity,
	ad_id int not null,
	customer_id int not null,
	date_bid date not null,
	price_bid numeric not null,
	status_bid varchar(20) default 'Sent' not null,
	primary key(bid_id),
	check (price_bid > 0),
	check (status_bid in ('Sent','Cancelled')),
	constraint fk_bids_ads
		foreign key(ad_id)
		references ads(ad_id),
	constraint fk_bids_customers
		foreign key(customer_id)
		references customers(customer_id)
);
